export const DATA_TEST_ID = {
    createNewTrainingButton: 'create-new-training-button',
    modalNoReview: 'modal-no-review',
    modalErrorUserTrainingTitle: 'modal-error-user-training-title',
    modalErrorUserTrainingSubTitle: 'modal-error-user-training-subtitle',
    modalErrorUserTrainingButton: 'modal-error-user-training-button',
    modalErrorUserTrainingButtonClose: 'modal-error-user-training-button-close',
    menuButtonTraining: 'menu-button-training',
    menuButtonCalendar: 'menu-button-calendar',
    menuButtonProfile: 'menu-button-profile',
    modalCreateTraining: 'modal-create-training',
    modalCreateTrainingButtonClose: 'modal-create-training-button-close',
    modalUpdateTrainingEditButton: 'modal-update-training-edit-button',
    modalCreateExercise: 'modal-create-exercise',
    modalCreateExerciseButton: 'modal-create-exercise-button',
    modalCreateExerciseSelect: 'modal-create-exercise-select',
    modalExerciseTrainingButtonClose: 'modal-exercise-training-button-close',

    modalDrawerRight: 'modal-drawer-right',
    modalDrawerRightButtonClose: 'modal-drawer-right-button-close',
    modalDrawerRightInputExercise: 'modal-drawer-right-input-exercise',
    modalDrawerRightCheckboxExercise: 'modal-drawer-right-checkbox-exercise',
    modalDrawerRightInputApproach: 'modal-drawer-right-input-approach',
    modalDrawerRightInputWeight: 'modal-drawer-right-input-weight',
    modalDrawerRightInputQuantity: 'modal-drawer-right-input-quantity',
    modalDrawerRightDatePicker: 'modal-drawer-right-date-picker',
    modalDrawerRightCheckboxPeriod: 'modal-drawer-right-checkbox-period',
    modalDrawerRightSelectPeriod: 'modal-drawer-right-select-period',

    myTrainingsTable: 'my-trainings-table',
    updateMyTrainingTableIcon: 'update-my-training-table-icon',
    createTrainingSuccessAlert: 'create-training-success-alert',
    searchInput: 'search-input',
    jointTrainingCards: 'joint-training-cards',
    notificationAboutJointTraining: 'notification-about-joint-training',
    jointTrainingReviewCard: 'joint-training-review-card',
    partnerModal: 'partner-modal',
    loader: 'loader',
    sidebarAchievements: 'sidebar-achievements',
};
